package com.example.courseworkfx;

public class Stations {
    String[] stations = {
            "Abanpola, North Western Province",
            "Agbopura, Eastern Province",
            "Ahangama, Southern Province",
            "Ahungalle, Southern Province",
            "Akurala, Southern Province",
            "Akurala",
            "Alawwa, North Western Province",
            "Alawwa",
            "Alawathupitiya,",
            "Aluthgama, Western Province",
            "Aluthgama",
            "Ambalangoda, Southern Province",
            "Ambepussa, Western Province",
            "Ambewela, Central Province",
            "Angulana, Western Province",
            "Anuradhapura, New Town",
            "Anuradhapura",
            "Arachchikattuwa",
            "Avissawella",
            "Badulla, Uva Province",
            "Balapitiya, Southern Province",
            "Babarenda, Southern Province",
            "Bambalapitiya, Western Province",
            "Bandarawela, Uva Province",
            "Bangadeniya, North Western Province",
            "Batticaloa, Eastern Province - terminus",
            "Batuwatta, Western Province",
            "Bemmulla, Western Province",
            "Beliatta, Southern Province",
            "Bentota, Southern Province",
            "Beruwala, Western Province",
            "Boossa, Southern Province",
            "Bothale, Western Province",
            "Bulugahoda, Western Province",
            "Chavakachcheri, Northern Province",
            "Chenkaladi, Eastern Province",
            "Chilaw, North Western Province",
            "Chunnakam, Northern Province",
            "Colombo Fort, Western Province",
            "Colombo, Western Province (currently the National Railway Museum, Colombo)",
            "Dematagoda, Western Province",
            "Daraluwa, Western Province",
            "Dehiwala, Western Province",
            "Demodara, Uva Province",
            "Diyatalawa, Uva Province",
            "Egoda Uyana, Western Province",
            "Elephant Pass, Northern Province",
            "Eluthumadduval, Northern Province",
            "Enderamulla, Western Province",
            "Free Trade Zone (formerly Katunayake South), Western Province",
            "Galle, Southern Province - terminus being extended",
            "Gampaha, Western Province",
            "Gampola, Central Province",
            "Ganemulla, Western Province",
            "Ganewatta, North Western Province",
            "Gintota, Southern Province",
            "Habaraduwa, Southern Province",
            "Habarane, North Central Province",
            "Halawatha",
            "Hali Ela, Uva Province",
            "Haputale, Uva Province",
            "Hath Amuna, North Central Province",
            "Hatton, Central Province",
            "Hettimulla, Western Province",
            "Hikkaduwa, Southern Province",
            "Hindeniya-Pattigoda, Western Province",
            "Hingurakgoda, North Central Province",
            "Horape, Western Province",
            "Hunupitiya, Western Province",
            "Horiwila, North Central Province",
            "Idalgashinna, Uva Province",
            "Induruwa, Southern Province",
            "Inuvil, Jaffna District, Northern Province",
            "Ja-Ela, Western Province",
            "Jaffna, Northern Province",
            "Jayanthipura, North Central Province",
            "Kahawa, Southern Province",
            "Kalutara North, Western Province",
            "Kalutara South, Western Province",
            "Kamburugamuwa, Southern Province",
            "Kandana, Western Province",
            "Kandy, Central Province",
            "Kankesanthurai, Northern Province - terminus",
            "Kantalai, Eastern Province",
            "Kapuwatte, Western Province",
            "Kataragama, Southern Province",
            "Kathaluwa, Southern Province",
            "Katugoda, Southern Province",
            "Katukurunda, Western Province",
            "Katunayake railway station, Western Province",
            "Katunayake railway station",
            "Katunayake Airport (BIA), Western Province",
            "Katunayake Airport (BIA)",
            "Keenawala, Western Province",
            "Kekanadura, Southern Province",
            "Kekirawa, North Central Province",
            "Kelaniya, Western Province",
            "Kilinochchi, Northern Province",
            "Kinigama, Uva Province",
            "Kodikamamam, Northern Province",
            "Koggala, Southern Province",
            "Kokgala, Southern Province",
            "Kookuvil, Northern Province",
            "Kollupitiya, Western Province",
            "Kondavil, Northern Province",
            "Koralawella, Western Province",
            "Kosgoda, Southern Province",
            "Kotugoda, Western Province",
            "Kudahakapola, Western Province",
            "Kurunegala, North Western Province",
            "Laxauyana, North Central Province",
            "Liyanagemulla, Western Province",
            "Lunawa, Western Province",
            "Lunuwila, North Western Province",
            "Magalegoda, Western Province",
            "Maggona, Western Province",
            "Maharagama, Western Province",
            "Maho, North Western Province",
            "Mallakam, Northern Province",
            "Manampitiya, North Central Province",
            "Mankulam, Northern Province",
            "Mannar, Northern Province",
            "Maradana, Western Province",
            "Matale, Central Province - terminus",
            "Matara, Southern Province",
            "Maviddapuram, Northern Province",
            "Medawachchiya, North Central Province",
            "Meesalai, Northern Province",
            "Mirigama, Western Province",
            "Mirissa, Southern Province",
            "Mirusuvil, Northern Province",
            "Moratuwa, Western Province",
            "Mount Lavinia, Western Province",
            "Murikandy, Northern Province",
            "Murikandy Temple, Northern Province",
            "Naththandiya, North Western Province",
            "Navatkuly, Northern Province",
            "Negombo, Western Province",
            "Nugegoda, Western Province",
            "Nanu Oya, Central Province",
            "Nawalapitiya, Central Province - Operation Control Office",
            "Ohiya, Uva Province",
            "Omanthai, Northern Province",
            "Padukka, Western Province",
            "Palai, Northern Province",
            "Pallewela, Western Province",
            "Parakum Uyana, North Central Province",
            "Paranthan, Northern Province",
            "Pattipola, Central Province",
            "Payagala North, Western Province",
            "Payagala South, Western Province",
            "Peradeniya Junction, Central Province - terminus",
            "Perelman day, Western Province",
            "Piladuwa, Southern Province",
            "Pilimathalawa, Central Province",
            "Pinwatta, Western Province",
            "Polgahawela Junction, North Western Province",
            "Polonnaruwa, North Central Province",
            "Polwathumodara, Southern Province",
            "Puliyahkulam, Northern Province",
            "Punkankulam, Northern Province",
            "Puttalam, North Western Province - branch terminus",
            "Polgahawela Junction",
            "Ragama, Western Province",
            "Rambukkana, Sabaragamuwa Province",
            "Rathmalane, Western Province",
            "Richmond Hill, Southern Province",
            "Radella, Central Province",
            "Rozella, Central Province",
            "Sankathanai, Northern Province",
            "Sarasavi Uyana, Central Province",
            "Seeduwa, Western Province",
            "Sewanapitiya, North Central Province",
            "Slave Island, Western Province",
            "Talaimannar, Northern Province - terminus, ferry port",
            "Talpe, Southern Province",
            "Tellipalai, Northern Province",
            "Thachanthoppu, Northern Province",
            "Telwatte, Southern Province",
            "Thandikulam, Northern Province",
            "Trincomalee, Eastern Province - terminus, ocean port",
            "Thambutthegama, North Central Province",
            "Thembiligala, Central Province",
            "Ukuwela - Central Province",
            "Unawatuna, Southern Province",
            "Ulapane, Central Province",
            "Valaichchenai, Eastern Province",
            "Vavuniya, Northern Province",
            "Veyangoda, Western Province",
            "Wadduwa, Western Province",
            "Walpola, Western Province",
            "Wanawasala, Western Province",
            "Wandurawa, Western Province",
            "Wattegama - Central Province",
            "Welikanda, North Central Province",
            "Weligama, Southern Province",
            "Wellawatta, Western Province",
            "Wijayarajadahana, Western Province",
            "Wavurukannala, Southern Province",
            "Yagoda, Western Province",
            "Yaththalgoda, Western Province"
    };

    String [] timeArr ={"12:00AM","12:30AM","1:00AM","1:30AM"};
    String [] timeDep ={"12:00PM","12:30PM","1:00PM","1:30PM"};
}
